### ISSUE TITLE
When clicking on class constructor it doesn't jump to it

### ISSUE THREAD

**Issue by mingodad** [vovkos/jancy_b#3]
After successfully build the latest `Jancy` and testing the `jnc_mini_ide` with `jancy/samples/jnc/02_Inheritance.jnc` and when clicking on class constructors in the `module` window `C1 -> void construct(C1 safe* this, int a)` the editor `cursor` jumps to line 1 instead of the line 33.

**Comment by mingodad** [comment]
It doesn't jump correcctly when clicking on destructors too.

**Comment by mingodad** [comment]
Also would be nice that it scroll to the center of the editor window instead of the bottom of it.

**Comment by vovkos** [comment]
Fixed in commits: 
https://github.com/vovkos/jancy/commit/0ed18a3c0f33df9e9650b11d45f33a57ff6c573a
https://github.com/vovkos/jancy/commit/0d5ba3af7bbe38ef515f08bc6e7dda8fce79f67f
